application: hw-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /cancel_register
  script: cancel_register.py
- url: /register
  script: register.py 
- url: /update
  script: update.py
- url: /dept
  script: dept.py
- url: /doctor
  script: doctor.py
- url: /clean
  script: clean.py
- url: /.*
  script: helloworld.py
