application: hw-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /ntuh/cancel_register
  script: cancel_register.py
- url: /ntuh/register
  script: register.py 
- url: /ntuh/update
  script: update.py
- url: /ntuh/dept
  script: dept.py
- url: /ntuh/doctor
  script: doctor.py
- url: /ntuh/clean
  script: clean.py
- url: /.*
  script: helloworld.py
